package entity;
// Generated 6/12/2017 09:09:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private String nombregrupo;
     private Set diagramas = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String nombregrupo) {
        this.nombregrupo = nombregrupo;
    }
    public Grupo(String nombregrupo, Set diagramas, Set usuarioses) {
       this.nombregrupo = nombregrupo;
       this.diagramas = diagramas;
       this.usuarioses = usuarioses;
    }
   
    public String getNombregrupo() {
        return this.nombregrupo;
    }
    
    public void setNombregrupo(String nombregrupo) {
        this.nombregrupo = nombregrupo;
    }
    public Set getDiagramas() {
        return this.diagramas;
    }
    
    public void setDiagramas(Set diagramas) {
        this.diagramas = diagramas;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


