package entity;
// Generated 6/12/2017 09:09:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUser;
     private String userNameIn;
     private String passwordIn;
     private String tipoIn;
     private Set grupos = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String userNameIn, String passwordIn, String tipoIn) {
        this.userNameIn = userNameIn;
        this.passwordIn = passwordIn;
        this.tipoIn = tipoIn;
    }
    public Usuarios(String userNameIn, String passwordIn, String tipoIn, Set grupos) {
       this.userNameIn = userNameIn;
       this.passwordIn = passwordIn;
       this.tipoIn = tipoIn;
       this.grupos = grupos;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUserNameIn() {
        return this.userNameIn;
    }
    
    public void setUserNameIn(String userNameIn) {
        this.userNameIn = userNameIn;
    }
    public String getPasswordIn() {
        return this.passwordIn;
    }
    
    public void setPasswordIn(String passwordIn) {
        this.passwordIn = passwordIn;
    }
    public String getTipoIn() {
        return this.tipoIn;
    }
    
    public void setTipoIn(String tipoIn) {
        this.tipoIn = tipoIn;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


